const pool = require('../config/db');

exports.createComplaint = async (req, res) => {
  try {
    const { userId, title, description, imageUrl } = req.body;
    const resolvedUserId = userId || null;
    
    const [result] = await pool.query(
      'INSERT INTO complaints (userId, title, description, status, imageUrl) VALUES (?, ?, ?, ?, ?)', 
      [resolvedUserId, title || 'AI Audit Upload', description || 'Generated by interface', 'pending', imageUrl || null]
    );
    res.status(201).json({ success: true, message: "Complaint logged to DB", complaintId: result.insertId });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};
